version: "3.3"
services: 
    frontend: 
        build: ./todo-frontend
        ports: 
            - 3000:80
        depends_on: 
            - graphql
        networks: 
            - todo-networks
        container_name: nginx
        image: frontend
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    graphql: 
        build: ./todo-backend
        ports: 
            - 4000:4000
        networks: 
            - todo-networks
    
networks: 
    todo-networks:
